uint8 STATUS_UNKNOWN = 0
uint8 STATUS_ACCEPTED = 1
uint8 STATUS_REJECTED = 2
uint8 STATUS_SUCCEEDED = 3
uint8 STATUS_CANCELED = 4
uint8 STATUS_ABORTED = 5

# request
string mission_uuid
uint8 mission_state
---
# response
bool result
